name: app
description: "XZIP"

publish_to: "none"
version: 1.0.2+3

environment:
  sdk: ^3.5.3
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: 2.4.4
  flutter_bloc: 8.1.6
  get_it: 7.7.0
  dartz: ^0.10.1
  flutter_svg: 2.0.10+1
  json_annotation: 4.9.0
  intl: 0.20.2
  equatable: 2.0.5
  injectable: 2.3.0
  logger: 2.4.0
  shared_preferences: 2.3.2
  flutter_screenutil: 5.9.3
  fluro: ^2.0.5
  lottie: ^3.1.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.12
  freezed: ^2.5.2
  mockito: 5.4.4
  json_serializable: 6.8.0
  injectable_generator: 2.4.0
  flutter_gen_runner: 5.7.0
  flutter_lints: 4.0.0

flutter_gen:
  output: lib/core/gen/assets.gen.dart
  synthetic-package: false
  integrations:
    flutter_svg: true
  fonts:
    enabled: false
  colors:
    enabled: false

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
